### ISSUE TITLE
les 6 Final Assingment NS.py

### ISSUE THREAD

**Issue by aschwinwester** [AmberKramer/Programming1#4]
1. Weekend moet een boolean zijn.
2. ritprijs dient als return waarde de ritprijs terug te geven.

**Comment by AmberKramer** [comment]
De Eindprijs wordt nu gereturned aan het einde van ritprijs. Ik heb besloten om weekend niet aan te passen, omdat een gebruiker niet zelf True of False zou invullen als input, maar Nederlands zou gebruiken en ja of nee zou invullen.
